### PR TITLE
Update react so it's 17/18 

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
We want to use this lib in one project that has `React 18` and one that has `React 17`.

@brumik

### CODE REVIEW

**Comment by brumik** [comment]
Oh wow it's nice to see that it's still used, so I guess it's working miracles if more teams using it?

I can approve this but I need to ask you to update the commit message. We are using scematic release, I think this is a `feat` since it is backwards compatible:  https://github.com/brumik/react-json-chart-builder#semantic-release-commit-messages

**Comment by ZitaNemeckova** [comment]
@brumik Still only used by Analytics now but we'll be working on bringing it to https://github.com/ansible/ansible-ui and maybe AWX will use it too.

**Comment by brumik** [comment]
If you need features in limited time I am happy to help, worked on one more generalization project (for quick real world UI designs :D if you are interested I can send it), so I could do waaaay better here. Also it seems PF charts fixed some undelying issues with their lib, so that could help.

**Review by brumik — APPROVED** [review]

**Comment by brumik** [comment]
@ZitaNemeckova the GH workflows changed in the last year so we need to fix semantic release. If you can do it or need this fast, could you do it? I can only do it 2 weeks from now.

**Comment by ZitaNemeckova** [comment]
@brumik I need it ASAP so I'll work on it next week. Thanks :)

**Comment by brumik** [comment]
Thanks!

**Pull request merged**
