### PR TITLE
chore(dep): Update patternfly deps

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
Updating PF deps to be compatible with https://github.com/ansible/ansible-ui/blob/main/package.json#L60-L61

### CODE REVIEW

**Review by brumik — CHANGES_REQUESTED** [review]
LGTM, maybe we can say react-code >4.214.X and charts >6.67 since patternfly using the semantic release versioning too (so all features should be backwards compatible

**Comment by ZitaNemeckova** [comment]
@brumik I'm not sure with deps. So I'll post the error from ansible-ui
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @ansible/ansible-ui@0.0.593
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!   peer react@"^16.8 || ^17 || ^18" from @patternfly/react-charts@6.94.18
npm ERR!   node_modules/@patternfly/react-charts
npm ERR!     @patternfly/react-charts@"6.94.18" from the root project
npm ERR!     peer @patternfly/react-charts@"^6.67.1" from react-json-chart-builder@1.14.1
npm ERR!     node_modules/react-json-chart-builder
npm ERR!       react-json-chart-builder@"^1.14.1" from the root project
npm ERR!   2 more (react-dom, @patternfly/react-core)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2 | ^18" from react-json-chart-builder@1.14.1
npm ERR! node_modules/react-json-chart-builder
npm ERR!   react-json-chart-builder@"^1.14.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/zita/.npm/_logs/2023-03-21T14_24_36_873Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zita/.npm/_logs/2023-03-21T14_24_36_873Z-debug-0.log
```

**Review by brumik — APPROVED** [review]

**Comment by ZitaNemeckova** [comment]
@brumik I think I messed up with the commit message. `chore` is not gonna trigger a new release, right?

**Comment by ZitaNemeckova** [comment]
@brumik Could you trigger the release manually, please?

**Comment by brumik** [comment]
Let me get to a terminal, i think I'll just push a fix commit with empty changes nearly

**Comment by ZitaNemeckova** [comment]
Thank you :)

**Pull request merged**
